import {
  BadgeDollarSign,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  ClipboardCheck,
  Clock3,
  Database,
  HardHat,
  HeartHandshake,
  Hospital,
  Mail,
  MessageCircleMore,
  PhoneCall,
  Scale,
  ShieldCheck,
  Sparkles,
  Star,
  Store,
  SunMedium,
  Target,
  TrendingUp,
  WalletCards,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const icons: Record<string, LucideIcon> = {
  phone: PhoneCall,
  'follow-up': MessageCircleMore,
  calendar: CalendarDays,
  mail: Mail,
  database: Database,
  support: HeartHandshake,
  clipboard: ClipboardCheck,
  sparkles: Sparkles,
  target: Target,
  workflow: Workflow,
  star: Star,
  clock: Clock3,
  zap: Zap,
  trending: TrendingUp,
  wallet: WalletCards,
  scale: Scale,
  sun: SunMedium,
  heart: HeartHandshake,
  shield: ShieldCheck,
  medical: Hospital,
  building: Building2,
  'hard-hat': HardHat,
  briefcase: BriefcaseBusiness,
  store: Store,
  money: BadgeDollarSign,
}

export function Icon({ name, className = '' }: { name: string; className?: string }) {
  const Component = icons[name] ?? Sparkles
  return <Component aria-hidden="true" className={className} strokeWidth={1.7} />
}
